import mdtraj as md
import numpy as np
from pathlib import Path
from typing import List, Optional, Union
import torch
from metastategen.utils import get_logger

log = get_logger("io_formats")

def get_ala2_topology():
    """
    Returns a hardcoded mdtraj Topology for Alanine Dipeptide (ACE-ALA-NME).
    This ensures that output files have correct residue and atom names.
    
    Structure: ACE(1) - ALA(2) - NME(3)
    Heavy Atoms (22 total atoms in structure, but this function defines topology)
    """
    top = md.Topology()
    chain = top.add_chain()
    
    # Residue 1: ACE
    res_ace = top.add_residue("ACE", chain)
    # Atoms in ACE: CH3, C, O
    # But usually structures just have CH3, C, O or H3, C, O. 
    # Standard Ala2 usually starts with H1, C1, H2, H3 (CH3 group) then C, O.
    # We need to match the 22-atom template ordering EXACTLY.
    # 22-atom template order (standard CHARMM/AMBER):
    # 0: CH3 (C_ACE)
    # 1: H
    # 2: H
    # 3: H
    # 4: C (C_ACE_Carbonyl)
    # 5: O
    # 6: N (ALA)
    # 7: H
    # 8: CA
    # 9: HA
    # 10: CB
    # 11: HB1
    # 12: HB2
    # 13: HB3
    # 14: C (ALA_Carbonyl)
    # 15: O
    # 16: N (NME)
    # 17: H
    # 18: CH3 (C_NME)
    # 19: H
    # 20: H
    # 21: H
    
    # Let's create atoms in this order
    
    # ACE
    a0 = top.add_atom("CH3", md.element.carbon, res_ace)
    top.add_atom("H1", md.element.hydrogen, res_ace)
    top.add_atom("H2", md.element.hydrogen, res_ace)
    top.add_atom("H3", md.element.hydrogen, res_ace)
    top.add_atom("C", md.element.carbon, res_ace)
    top.add_atom("O", md.element.oxygen, res_ace)
    
    # ALA
    res_ala = top.add_residue("ALA", chain)
    top.add_atom("N", md.element.nitrogen, res_ala)
    top.add_atom("H", md.element.hydrogen, res_ala)
    top.add_atom("CA", md.element.carbon, res_ala)
    top.add_atom("HA", md.element.hydrogen, res_ala)
    top.add_atom("CB", md.element.carbon, res_ala)
    top.add_atom("HB1", md.element.hydrogen, res_ala)
    top.add_atom("HB2", md.element.hydrogen, res_ala)
    top.add_atom("HB3", md.element.hydrogen, res_ala)
    top.add_atom("C", md.element.carbon, res_ala)
    top.add_atom("O", md.element.oxygen, res_ala)
    
    # NME
    res_nme = top.add_residue("NME", chain)
    top.add_atom("N", md.element.nitrogen, res_nme)
    top.add_atom("H", md.element.hydrogen, res_nme)
    top.add_atom("CH3", md.element.carbon, res_nme)
    top.add_atom("H1", md.element.hydrogen, res_nme)
    top.add_atom("H2", md.element.hydrogen, res_nme)
    top.add_atom("H3", md.element.hydrogen, res_nme)
    
    return top

def save_lammps_data(
    positions: np.ndarray, 
    out_path: Union[str, Path], 
    box_size: float = 10.0
):
    """
    Writes a basic LAMMPS data file (geometry only, no topology/forcefield).
    Assumes all atoms are same type or simple mapping if needed. 
    Here we just give them ID 1..N.
    """
    pos = positions # [N, 3]
    n_atoms = pos.shape[0]
    
    with open(out_path, 'w') as f:
        f.write("Generated by MetaStateGen\n\n")
        f.write(f"{n_atoms} atoms\n")
        f.write("1 atom types\n\n")
        
        # Box
        f.write(f"{-box_size/2:.2f} {box_size/2:.2f} xlo xhi\n")
        f.write(f"{-box_size/2:.2f} {box_size/2:.2f} ylo yhi\n")
        f.write(f"{-box_size/2:.2f} {box_size/2:.2f} zlo zhi\n\n")
        
        f.write("Atoms\n\n")
        for i in range(n_atoms):
            # ID type x y z
            f.write(f"{i+1} 1 {pos[i, 0]:.5f} {pos[i, 1]:.5f} {pos[i, 2]:.5f}\n")
            
    log.info(f"Saved LAMMPS data to {out_path}")

def save_outputs(
    positions: torch.Tensor,
    out_dir: Union[str, Path],
    formats: List[str],
    prefix: str = "refined",
    topology: Optional[md.Topology] = None
):
    """
    Saves positions in requested formats.
    
    Args:
        positions: [B, N, 3] tensor of coordinates (nm)
        out_dir: Output directory
        formats: List of formats ('pdb', 'gro', 'xyz', 'lammps_dump', 'lammps_data')
        topology: Optional mdtraj Topology. If None, defaults to hardcoded Ala2.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    
    # Convert to numpy and nm
    pos_np = positions.cpu().numpy()
    
    # Get Topology
    if topology is None:
        log.warning("No topology provided to save_outputs. Defaulting to hardcoded Ala2 (22 atoms).")
        top = get_ala2_topology()
    else:
        top = topology
    
    # Create Trajectory
    traj = md.Trajectory(pos_np, top)
    
    # Set unit cell dimensions (10nm box default)
    traj.unitcell_lengths = np.ones((traj.n_frames, 3)) * 10.0
    traj.unitcell_angles = np.ones((traj.n_frames, 3)) * 90.0
    
    # Save requested formats
    for fmt in formats:
        fmt = fmt.lower()
        
        if fmt == 'pdb':
            out_path = out_dir / f"{prefix}.pdb"
            traj.save_pdb(str(out_path))
            log.info(f"Saved {out_path}")
            
        elif fmt == 'gro':
            out_path = out_dir / f"{prefix}.gro"
            traj.save_gro(str(out_path))
            log.info(f"Saved {out_path}")
            
        elif fmt == 'xyz':
            out_path = out_dir / f"{prefix}.xyz"
            traj.save_xyz(str(out_path))
            log.info(f"Saved {out_path}")
            
        elif fmt == 'lammps_dump':
            out_path = out_dir / f"{prefix}.lammpstrj"
            traj.save_lammpstrj(str(out_path))
            log.info(f"Saved {out_path}")
            
        elif fmt == 'lammps_data':
            # Save first frame only for data file
            out_path = out_dir / f"{prefix}.data"
            save_lammps_data(pos_np[0] * 10, str(out_path)) # nm -> angstrom usually for LAMMPS? MDTraj uses nm. LAMMPS units vary. Let's stick to nm (input units). 
            # WAIT: MDTraj is nm. LAMMPS 'real' is Angstrom, 'lj' is unitless. 
            # If user asks for LAMMPS they usually expect Angstroms if using real/metal.
            # Let's assume Angstroms for LAMMPS data file generally.
            save_lammps_data(pos_np[0] * 10.0, str(out_path), box_size=100.0) 
            log.info(f"Saved {out_path} (Angstroms)")
            
        elif fmt == 'amber_rst':
            out_path = out_dir / f"{prefix}.rst7"
            traj[0].save_amberrst7(str(out_path))
            log.info(f"Saved {out_path}")
            
        else:
            log.warning(f"Unknown format: {fmt}")
