import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import argparse
import sys
from pathlib import Path
# Fix for legacy sklearn with new numpy
if not hasattr(np, 'float'):
    np.float = float
from sklearn.cluster import DBSCAN

# Ensure we can import regions
sys.path.append(str(Path(__file__).parent))
from regions import plot_regions

def get_cluster_centers(phi, psi, eps=0.4, min_samples=20, top_n=5):
    # Convert to circular coordinates
    phi_rad = np.radians(phi)
    psi_rad = np.radians(psi)
    
    X = np.column_stack([
        np.cos(phi_rad), np.sin(phi_rad),
        np.cos(psi_rad), np.sin(psi_rad)
    ])
    
    # DBSCAN
    scan = DBSCAN(eps=eps, min_samples=min_samples).fit(X)
    labels = scan.labels_
    
    unique_labels = set(labels)
    if -1 in unique_labels:
        unique_labels.remove(-1)
        
    clusters = []
    
    for lab in unique_labels:
        mask = labels == lab
        count = np.sum(mask)
        
        # Mean vector
        mean_vec = np.mean(X[mask], axis=0)
        mean_phi = np.degrees(np.arctan2(mean_vec[1], mean_vec[0]))
        mean_psi = np.degrees(np.arctan2(mean_vec[3], mean_vec[2]))
        
        clusters.append({
            "label": lab,
            "count": count,
            "phi": mean_phi,
            "psi": mean_psi
        })
        
    # Sort by count descending
    clusters.sort(key=lambda x: x["count"], reverse=True)
    return clusters[:top_n], labels

def main():
    parser = argparse.ArgumentParser(description="Analyze Clusters in Phi-Psi Data")
    parser.add_argument("--data", type=str, required=True, help="Path to evolution_data.csv (generated by viz_density.py)")
    parser.add_argument("--outdir", type=str, default="analysis_outputs", help="Directory to save analysis")
    
    args = parser.parse_args()
    
    csv_path = Path(args.data)
    out_dir = Path(args.outdir)
    
    if not csv_path.exists():
        print(f"Error: Data file {csv_path} not found.")
        return

    out_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(csv_path)
    if 'Iter' not in df.columns:
        print("Error: CSV must have 'Iter', 'Phi', 'Psi' columns.")
        return
        
    iters = sorted(df['Iter'].unique())
    
    num_plots = len(iters)
    fig, axes = plt.subplots(1, num_plots, figsize=(6 * num_plots, 6), sharex=True, sharey=True)
    if num_plots == 1:
        axes = [axes]
    
    print(f"{'Iter':<5} | {'Cluster':<7} | {'Phi':>7} | {'Psi':>7} | {'Count':>5} | {'Description'}")
    print("-" * 65)
    
    cluster_rows = []
    
    for i, ax in zip(iters, axes):
        subset = df[df['Iter'] == i]
        phi = subset['Phi'].values
        psi = subset['Psi'].values
        
        # Run Clustering
        # Relaxed threshold: eps=0.28 (approx 16 degrees radius)
        top_clusters, labels = get_cluster_centers(phi, psi, eps=0.28, min_samples=15)
        
        # PLOT
        ax.set_aspect('equal')
        
        # Plot noise
        noise_mask = labels == -1
        ax.scatter(phi[noise_mask], psi[noise_mask], c='lightgrey', s=5, alpha=0.3, label='Noise')
        
        unique_valid = sorted(list(set(labels) - {-1}))
        
        for lab in unique_valid:
            mask = labels == lab
            rank = -1
            for r, tc in enumerate(top_clusters):
                if tc['label'] == lab:
                    rank = r
                    break
            
            if rank != -1:
                 alpha=0.6
                 label_text = f"C{rank+1}" 
            else:
                 alpha=0.2
                 label_text = None

            ax.scatter(phi[mask], psi[mask], s=10, alpha=alpha, label=label_text)
            
        ax.set_title(f"Iter {i}")
        ax.set_xlabel("Phi")
        if i == iters[0]: ax.set_ylabel("Psi")
        ax.set_xlim(-180, 180)
        ax.set_ylim(-180, 180)
        
        # Print and plot centroids
        for rank, c in enumerate(top_clusters):
            cx, cy = c['phi'], c['psi']
            
            ax.plot(cx, cy, 'kX', markersize=10, markeredgecolor='white')
            ax.text(cx+5, cy+5, str(rank+1), fontsize=12, fontweight='bold', color='black')
            
            # Annotations logic
            desc = "Unknown"
            if -100 <= cx <= -40 and -80 <= cy <= -10: desc = "Alpha_R"
            elif (cx <= -60 or cx >= 150) and (abs(cy) >= 90): desc = "Beta/C5"
            elif -120 <= cx <= -40 and 0 <= cy <= 100: desc = "C7eq"
            elif 30 <= cx <= 90 and -90 <= cy <= -30: desc = "C7ax"
            elif 30 <= cx <= 90 and 0 <= cy <= 80: desc = "Alpha_L"
            elif -25 <= cx <= 25 and -25 <= cy <= 25: desc = "Barrier"

            print(f"{i:<5} | #{rank+1:<6} | {cx:>7.1f} | {cy:>7.1f} | {int(c['count']):>5} | {desc}")
            
            cluster_rows.append({
                "Iter": i,
                "Rank": rank + 1,
                "Phi": round(cx, 2),
                "Psi": round(cy, 2),
                "Count": int(c['count']),
                "Description": desc
            })

        plot_regions(ax)
        
    plt.suptitle("Cluster Analysis (Top Clusters per Iteration)")
    
    out_png = out_dir / "cluster_analysis.png"
    plt.savefig(out_png, dpi=150, bbox_inches='tight')
    print(f"\nSaved plot to {out_png}")

    if cluster_rows:
        csv_out = out_dir / "cluster_analysis_summary.csv"
        pd.DataFrame(cluster_rows).to_csv(csv_out, index=False)
        print(f"Saved CSV to {csv_out}")

if __name__ == "__main__":
    main()
